### ISSUE TITLE
Implement time limit for pace of play

### ISSUE THREAD

**Issue by akick31** [Watchful1/CFBRef#12]

**Comment by Watchful1** [comment]
Moving time limit to 1.1 since it's a bit complicated more complicated than I thought

**Comment by Watchful1** [comment]
In summary, if it has been 24 hours since any action was last taken in a game, the team that the game is waiting on suffers either a turnover if they have the ball, or a touchdown scored on them if they are the defense. They also receive a strike, and on the third strike, they forfeit the game.

If it has been 10 days since the game started, and the game is not currently in overtime, the game ends at the end of the current quarter. If the quarter ends with the score tied, the game proceeds to overtime. If game finishes two overtime periods still tied, a coin is flipped to determine the winner.

**Comment by Watchful1** [comment]
Add a system where an admin can message the bot and grant a delay on the 24 hours rule. The 10 day rule is then also extended by the same amount of time.
